package main

import (
	"fmt"
	"strings"
)

func httpHandlersContent(methods []serviceMethod) (string, error) {
	var operations strings.Builder
	var handlers strings.Builder
	for _, method := range methods {
		fmt.Fprintf(&operations, "\t{Descriptor: mustOperation(%q), Handler: %sHTTPHandler(s)},\n", method.Name, method.Name)
		handler, err := httpHandlerFunction(method, operationInputs(method))
		if err != nil {
			return "", err
		}
		handlers.WriteString(handler)
	}
	return formatGo(fmt.Sprintf(`// Code generated by creed-codegen; DO NOT EDIT.

package gen

import (
    "context"
    "encoding/json"
    "fmt"
    "strings"

    opsgen "github.com/techgodhq/creed/internal/ops/gen"
    "github.com/techgodhq/creed/internal/service"
    "github.com/techgodhq/creed/internal/usecase"
)

// OperationHandler invokes one generated HTTP operation with decoded JSON input.
type OperationHandler func(context.Context, json.RawMessage) (any, error)

// GeneratedOperation contains generated HTTP routing metadata and a handler.
type GeneratedOperation struct {
    Descriptor opsgen.OperationDescriptor
    Handler    OperationHandler
}

// GeneratedOperations returns all Service-derived HTTP operations and handlers.
func GeneratedOperations(s service.Service) []GeneratedOperation {
    return []GeneratedOperation{
%s    }
}

%s
func mustOperation(methodName string) opsgen.OperationDescriptor {
    operation, ok := opsgen.ByMethodName(methodName)
    if !ok {
        panic(fmt.Sprintf("generated HTTP operation %%s missing descriptor", methodName))
    }
    return operation
}

func decodePayload(payload json.RawMessage, dst any) error {
    if len(strings.TrimSpace(string(payload))) == 0 {
        payload = json.RawMessage(`+"`{} `"+`)
    }
    decoder := json.NewDecoder(strings.NewReader(string(payload)))
    decoder.DisallowUnknownFields()
    if err := decoder.Decode(dst); err != nil {
        return fmt.Errorf("decode HTTP operation payload: %%w", err)
    }
    return nil
}
`, operations.String(), handlers.String()))
}

func httpHandlerFunction(method serviceMethod, inputs []methodParam) (string, error) {
	requestType := lowerFirst(method.Name) + "Request"
	var b strings.Builder
	if len(inputs) > 0 {
		fmt.Fprintf(&b, "type %s struct {\n", requestType)
		for _, input := range inputs {
			fieldName := exportedName(input.Name)
			jsonTag := input.ExternalName
			if !input.Required {
				jsonTag += ",omitempty"
			}
			fmt.Fprintf(&b, "\t%s %s `json:%q`\n", fieldName, input.Type, jsonTag)
		}
		fmt.Fprintf(&b, "}\n\n")
	}
	fmt.Fprintf(&b, "// %sHTTPHandler returns the generated HTTP handler for service.Service.%s.\n", method.Name, method.Name)
	fmt.Fprintf(&b, "func %sHTTPHandler(s service.Service) OperationHandler {\n", method.Name)
	fmt.Fprintf(&b, "\treturn func(ctx context.Context, payload json.RawMessage) (any, error) {\n")
	if len(inputs) > 0 {
		fmt.Fprintf(&b, "\t\tvar req %s\n", requestType)
		fmt.Fprintf(&b, "\t\tif err := decodePayload(payload, &req); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		for _, input := range inputs {
			if input.Required && input.Type == "string" {
				fmt.Fprintf(&b, "\t\tif strings.TrimSpace(req.%s) == \"\" {\n\t\t\treturn nil, fmt.Errorf(%q)\n\t\t}\n", exportedName(input.Name), input.ExternalName+" is required")
			}
		}
	} else {
		fmt.Fprintf(&b, "\t\tif err := decodePayload(payload, &struct{}{}); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
	}
	callArgs, err := httpCallArgs(method, inputs)
	if err != nil {
		return "", err
	}
	if len(method.Results) == 1 && method.Results[0].Type == "error" {
		fmt.Fprintf(&b, "		if err := s.%s(%s); err != nil {\n			return nil, err\n		}\n", method.Name, callArgs)
		fmt.Fprintf(&b, "		return nil, nil\n")
	} else if len(method.Results) == 2 && method.Results[1].Type == "error" {
		fmt.Fprintf(&b, "\t\tresult, err := s.%s(%s)\n", method.Name, callArgs)
		fmt.Fprintf(&b, "\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		fmt.Fprintf(&b, "\t\treturn result, nil\n")
	} else {
		return "", fmt.Errorf("cannot generate HTTP handler for %s: unsupported result shape", method.Name)
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "}\n\n")
	return b.String(), nil
}

func httpCallArgs(method serviceMethod, inputs []methodParam) (string, error) {
	args := []string{}
	inputByName := map[string]methodParam{}
	for _, input := range inputs {
		inputByName[input.Name] = input
	}
	for _, param := range method.Params {
		switch param.Kind {
		case "context":
			args = append(args, "ctx")
		case "primitive":
			input, ok := inputByName[param.Name]
			if !ok {
				input = param
			}
			args = append(args, "req."+exportedName(input.Name))
		case "struct":
			if len(param.Fields) == 0 {
				return "", fmt.Errorf("cannot generate HTTP handler for %s.%s: struct inputs must be expanded into operation descriptor fields", method.Name, param.Name)
			}
			parts := []string{}
			for _, input := range param.Fields {
				parts = append(parts, fmt.Sprintf("%s: req.%s", exportedName(input.Name), exportedName(input.Name)))
			}
			args = append(args, fmt.Sprintf("%s{%s}", generatedTypeName(param.Type), strings.Join(parts, ", ")))
		default:
			return "", fmt.Errorf("cannot generate HTTP call for %s.%s kind %s", method.Name, param.Name, param.Kind)
		}
	}
	return strings.Join(args, ", "), nil
}
