// Package codegen implements the code generation tool that produces thin
// wrappers (CLI commands, MCP tools) from the Service interface.
//
// This is the scaffolding entrypoint — the full reflection-based generator
// is implemented in later PRs (T19). For now this provides the CLI
// structure and help text so the build system can wire go:generate.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

const helpText = `creed-codegen generates CLI and MCP surface code from the Service interface.

Usage:
  creed-codegen [flags]

Flags:
  --service PATH    Path to the service interface Go file (default: internal/service/service.go)
  --out-cli PATH    Output directory for generated CLI commands (default: cmd/gen)
  --out-mcp PATH    Output directory for generated MCP tools (default: internal/mcp/gen)
  --dry-run         Show what would be generated without writing files
  -h, --help        Show this help message

The generator reads the Service interface via Go reflection, extracts method
names, parameter types, and doc comments, then produces thin wrappers that
eliminate drift between CLI, MCP, and future HTTP surfaces.
`

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string) error {
	var (
		servicePath string
		outCLI      string
		outMCP      string
		dryRun      bool
		showHelp    bool
	)

	fs := flag.NewFlagSet("creed-codegen", flag.ContinueOnError)
	fs.StringVar(&servicePath, "service", "internal/service/service.go", "Path to the service interface Go file")
	fs.StringVar(&outCLI, "out-cli", "cmd/gen", "Output directory for generated CLI commands")
	fs.StringVar(&outMCP, "out-mcp", "internal/mcp/gen", "Output directory for generated MCP tools")
	fs.BoolVar(&dryRun, "dry-run", false, "Show what would be generated without writing files")
	fs.BoolVar(&showHelp, "help", false, "Show help message")
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, helpText)
	}
	if err := fs.Parse(args); err != nil {
		return err
	}
	if showHelp {
		fmt.Print(helpText)
		return nil
	}

	methods, err := serviceMethods(servicePath)
	if err != nil {
		return err
	}
	for _, method := range methods {
		name := snakeCase(method)
		if err := writeGeneratedFile(outCLI, name, method, "CLI", dryRun); err != nil {
			return err
		}
		if err := writeGeneratedFile(outMCP, name, method, "MCP", dryRun); err != nil {
			return err
		}
	}
	return nil
}

func serviceMethods(path string) ([]string, error) {
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse service file: %w", err)
	}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != "Service" {
				continue
			}
			iface, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok {
				return nil, fmt.Errorf("Service is not an interface")
			}
			methods := make([]string, 0, len(iface.Methods.List))
			for _, field := range iface.Methods.List {
				if len(field.Names) == 0 {
					continue
				}
				methods = append(methods, field.Names[0].Name)
			}
			return methods, nil
		}
	}
	return nil, fmt.Errorf("Service interface not found in %s", path)
}

func writeGeneratedFile(dir, name, method, surface string, dryRun bool) error {
	path := filepath.Join(dir, name+".go")
	if dryRun {
		fmt.Printf("would write %s\n", path)
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create output dir %s: %w", dir, err)
	}
	content := generatedContent(name, method, surface)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func generatedContent(name, method, surface string) string {
	switch surface {
	case "CLI":
		return fmt.Sprintf(`// Code generated by creed-codegen; DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/techgodhq/creed/internal/service"
)

// New%[2]sCommand returns the generated Cobra command wrapper for service.Service.%[2]s.
func New%[2]sCommand(s service.Service) *cobra.Command {
	cmd := &cobra.Command{
		Use:   %[1]q,
		Short: %[3]q,
		RunE: func(cmd *cobra.Command, args []string) error {
			_ = s
			return fmt.Errorf("generated command %[1]s is not wired yet")
		},
	}
	return cmd
}
`, name, method, method+" invokes service.Service."+method)
	case "MCP":
		return fmt.Sprintf(`// Code generated by creed-codegen; DO NOT EDIT.

package gen

// %[2]sToolName is the generated MCP tool name for service.Service.%[2]s.
const %[2]sToolName = %[1]q

// %[2]sToolDescription is the generated MCP tool description for service.Service.%[2]s.
const %[2]sToolDescription = %[3]q
`, name, method, method+" invokes service.Service."+method)
	default:
		return "// Code generated by creed-codegen; DO NOT EDIT.\n\npackage gen\n"
	}
}

func snakeCase(name string) string {
	var out strings.Builder
	for i, r := range name {
		if i > 0 && unicode.IsUpper(r) {
			out.WriteByte('_')
		}
		out.WriteRune(unicode.ToLower(r))
	}
	return out.String()
}
